project:
  type: website

website:
  page-navigation: true
  title: "Visual Analytics - Michael Djohan"
  description: "Homepage for my learning journey in visual analytics"
  site-url: "https://isss608-michaeldj.netlify.app/"
  
  sidebar: 
    background: "#282D33"
    logo: "images/icon.png"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/michaeldjo/ISSS608-VAA
      - icon: linkedin
        href: www.linkedin.com/in/michaelkevindjohan
  
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "About this website"
        contents: 
          - text: Home
            href: index.qmd
          - text: About 
            href: about.qmd
      - section: "Hands-on Exercise"
        contents: 
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 3"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
          - text: "Hands-on Exercise 4"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html" 
          - text: "Ternary Plot"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
          - text: "Hands-on Exercise 5"
            href: "Hands-on_Ex/Hands-on_Ex05.1/Hands-on_Ex05.1.html" 
          - text: "Hands-on Exercise 6"
            href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html" 
          - text: "Hands-on Exercise 7"
            href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html" 
          - text: "Hands-on Exercise 8"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html" 
          - text: "Hands-on Exercise 9"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.html" 
      - section: "In-Class Exercise"
        contents: 
          - text: "In-class Exercise 3"
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html" 
          - text: "In-class Exercise 4"
            href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html" 
          - text: "In-class Exercise 5"
            href: "In-class_Ex/In-class_Ex05/In-class_Ex05.html" 
      - section: "Take-home Exercise"
        contents: 
          - text: "Take-home Exercise 1"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
          - text: "Take-home Exercise 2"
            href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
          - text: "Take-home Exercise 3"
            href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html"
          - text: "Take-home Exercise 4"
            href: "Take-home_Ex/Take-home_Ex04/Take-home_Ex04.html"


format:
  html:
    theme: journal
    smooth-scroll: true
    css: styles.css
    toc: true

editor: visual

